### ISSUE TITLE
Switching language leaves MagicActions

### ISSUE THREAD

**Issue by LEdoian** [FHRNet/BakalariMagicActions#3]
When one switches language (in top left corner), the browser gets HTTP `302 Found` which redirects to the school server (instead of MagicActions).
School server does not have the language switched, but MagicActions do (e.g. when returning)
It should be possible to configure nginx to intercept the communication, but I didn't manage to do that.

**Comment by FHRNet** [comment]
Will fix.  
  
On Dec 14, 2016 13:18, LEdoian <notifications@github.com> wrote:When one switches language (in top left corner), the browser gets HTTP 302 Found which redirects to the school server (instead of MagicActions).
School server does not have the language switched, but MagicActions do (e.g. when returning)
It should be possible to configure nginx to intercept the communication, but I didn't manage to do that.
